//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataBaseControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smoothdbEntities : DbContext
    {
        public smoothdbEntities()
            : base("name=smoothdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cook_status> tb_cook_status { get; set; }
        public virtual DbSet<tb_customer> tb_customer { get; set; }
        public virtual DbSet<tb_employee> tb_employee { get; set; }
        public virtual DbSet<tb_employee_status> tb_employee_status { get; set; }
        public virtual DbSet<tb_employee_time_sheet> tb_employee_time_sheet { get; set; }
        public virtual DbSet<tb_ingredient> tb_ingredient { get; set; }
        public virtual DbSet<tb_level> tb_level { get; set; }
        public virtual DbSet<tb_location_menu> tb_location_menu { get; set; }
        public virtual DbSet<tb_location_tab> tb_location_tab { get; set; }
        public virtual DbSet<tb_order> tb_order { get; set; }
        public virtual DbSet<tb_order_detail> tb_order_detail { get; set; }
        public virtual DbSet<tb_order_status> tb_order_status { get; set; }
        public virtual DbSet<tb_order_type> tb_order_type { get; set; }
        public virtual DbSet<tb_payment_type> tb_payment_type { get; set; }
        public virtual DbSet<tb_popup> tb_popup { get; set; }
        public virtual DbSet<tb_popup_item> tb_popup_item { get; set; }
        public virtual DbSet<tb_printer> tb_printer { get; set; }
        public virtual DbSet<tb_printer_log> tb_printer_log { get; set; }
        public virtual DbSet<tb_printer_product> tb_printer_product { get; set; }
        public virtual DbSet<tb_product> tb_product { get; set; }
        public virtual DbSet<tb_section> tb_section { get; set; }
        public virtual DbSet<tb_setting> tb_setting { get; set; }
        public virtual DbSet<tb_table_section> tb_table_section { get; set; }
        public virtual DbSet<tb_type_food> tb_type_food { get; set; }
        public virtual DbSet<tb_product_ingredient> tb_product_ingredient { get; set; }
    }
}
