//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataBaseControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_employee_time_sheet
    {
        public int employee_time_sheet_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> clockin_time { get; set; }
        public Nullable<System.DateTime> clockout_time { get; set; }
    }
}
