//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataBaseControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_location_menu
    {
        public int tb_location_menu_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> tb_location_tab_id { get; set; }
        public Nullable<int> column_no { get; set; }
        public Nullable<int> row_no { get; set; }
        public int is_active { get; set; }
    }
}
