//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataBaseControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_order()
        {
            this.tb_order_detail = new HashSet<tb_order_detail>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_at { get; set; }
        public Nullable<int> order_type_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public int table { get; set; }
        public Nullable<int> order_status_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> is_active { get; set; }
    
        public virtual tb_customer tb_customer { get; set; }
        public virtual tb_employee tb_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_order_detail> tb_order_detail { get; set; }
        public virtual tb_order_status tb_order_status { get; set; }
        public virtual tb_order_type tb_order_type { get; set; }
        public virtual tb_payment_type tb_payment_type { get; set; }
    }
}
