//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataBaseControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_printer_log
    {
        public int printer_log_id { get; set; }
        public int printer_id { get; set; }
        public System.DateTime print_dt { get; set; }
        public string printer_detail { get; set; }
    
        public virtual tb_printer tb_printer { get; set; }
    }
}
