//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataBaseControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_product()
        {
            this.tb_order_detail = new HashSet<tb_order_detail>();
            this.tb_printer_product = new HashSet<tb_printer_product>();
        }
    
        public int product_id { get; set; }
        public string name { get; set; }
        public string short_name { get; set; }
        public string description { get; set; }
        public Nullable<sbyte> avaliable { get; set; }
        public Nullable<int> product_ingredient_id { get; set; }
        public Nullable<int> popup_id { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<float> price { get; set; }
        public string image_path { get; set; }
        public Nullable<int> type_food_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_order_detail> tb_order_detail { get; set; }
        public virtual tb_popup tb_popup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_printer_product> tb_printer_product { get; set; }
    }
}
