//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataBaseControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_table_section
    {
        public int table_section_id { get; set; }
        public string u_name { get; set; }
        public string name { get; set; }
        public Nullable<int> section_id { get; set; }
        public Nullable<float> margin_top { get; set; }
        public Nullable<float> margin_bottom { get; set; }
        public Nullable<float> margin_right { get; set; }
        public Nullable<float> margin_left { get; set; }
        public Nullable<float> height { get; set; }
        public Nullable<float> width { get; set; }
        public Nullable<int> is_active { get; set; }
    }
}
